### ISSUE TITLE
Using extern "C" to avoid name mangling

### ISSUE THREAD

**Issue by fmilano** [PlusToolkit/ndicapi#1]
Hi. I was looking for a C interface to connect to NDI cameras (using .NET platform invoke) and I have found yours. The design is great, it is (almost) pure C, since I have found two issues in the project as it is right now:

1) If you want the names in the generated .dll/.so libraries to be accesible by .NET or Java JNI, it is necessary for them to by unmangled. This is easily achieved in your project by adding extern "C" to the ndicapiExport definition.

2) There is (C++) function overloading (ndiTransformToMatrixd for example). Since C11 it is possible to overload C functions, but the mechanism is different from that of C++. Anyways, it is not recommended to export overloaded functions from a pure "C" interface. It would be very easy to change the function names according to the data type used in the call.

I will actually do these (very little) changes in my code. Do you think it may qualify for a pull request?

Thanks,

Federico

**Comment by adamrankin** [comment]
Definitely! Thanks for helping out.
