### ISSUE TITLE
Python package build fails due to missing Polaris module file

### ISSUE THREAD

**Issue by dzhoshkun** [PlusToolkit/ndicapi#10]
Running `python setup.py build` yields:

```
[0] % python setup.py build
running build
running build_ext
building 'polaris' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ndicapi.c -o build/temp.macosx-10.12-intel-2.7/ndicapi.o
clang: error: no such file or directory: 'ndicapi.c'
clang: error: no input files
error: command 'cc' failed with exit status 1
```

This problem can be solved by changing the [file extensions in `setup.py`](https://github.com/PlusToolkit/ndicapi/blob/15a21de7354eb608f9081e75a5babe820e627ce4/setup.py#L6) from `*.c` to `*.cxx`

Then the following error comes up:
```
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ndicapi.cxx -o build/temp.macosx-10.12-intel-2.7/ndicapi.o
In file included from ndicapi.cxx:39:
./ndicapi.h:43:10: fatal error: 'ndicapiExport.h' file not found
#include "ndicapiExport.h"
```

This can be resolved by `cmake`ing the project, which generates the missing `ndicapiExport.h` file from the [corresponding template file](https://github.com/PlusToolkit/ndicapi/blob/15a21de7354eb608f9081e75a5babe820e627ce4/ndicapiExport.h.in) (obviously, this `ndicapiExport.h` file needs to be copied to the main project folder where `python setup.py build` is run).

Subsequently the compilation fails due to:

```
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ndicapi_thread.cxx -o build/temp.macosx-10.12-intel-2.7/ndicapi_thread.o
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c polarismodule.c -o build/temp.macosx-10.12-intel-2.7/polarismodule.o
clang: error: no such file or directory: 'polarismodule.c'
clang: error: no input files
```

The `polarismodule.c` file is missing from the repository.
I was able to locate this file in [the AIGS repository](https://github.com/dgobbi/AIGS/blob/eb9db897aa642ad2fb65a4f2f51948049dd0010e/Utilities/ndicapi/polarismodule.c), which seems to have been committed in 2005, i.e. very old.

This PlusToolkit repository however is pretty up-to-date.
So I was wondering whether the `polarismodule.c` file was excluded due to any particular reason?

I'm on a MacBook Pro with macOS Sierra (Version 10.12.6) with Python 2.7.10 and CMake 3.7.2

**Comment by adamrankin** [comment]
Just goes to show... I had no idea there was even a python file in the repository!

I will apply your fixes and try and get this working.

**Comment by adamrankin** [comment]
After investigating, my conclusion is that the current python interface is dead. I will investigate if there are any more modern ways of wrapping C with python.

**Comment by adamrankin** [comment]
I was able to make some progress resurrecting the python interface. It is currently only a python2 extension module, and I've added some CMake to guard against that.

I am not familiar with python wrapping of C, so the compilation currently fails with the bitfield concept that David Gobbi implemented ages ago. If anyone is willing to fix it, that would be great.

**Comment by dzhoshkun** [comment]
@adamrankin Could you please provide more details about:

> I am not familiar with python wrapping of C, so the compilation currently fails with the bitfield concept that David Gobbi implemented ages ago.

I will try to spare some time to have a more in-depth look at this.

**Comment by dzhoshkun** [comment]
Also, thanks for the quick reply!

**Comment by adamrankin** [comment]
If you run setup.py again you will see the compilation errors. I am not familiar with the syntax of c python extensions.

**Comment by dzhoshkun** [comment]
This issue has been fixed now.
The module can be built and installed.
So closing this issue.

I'm trying to get it to actually work.
This is the current status: https://github.com/dzhoshkun/ndicapi/issues/4#issuecomment-365928800
