### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by Morwenn** [PlusToolkit/ndicapi#21]
Hi,

From what I can this project has versions (1.6.0 according to the CMakeLists.txt), but no corresponding releases or tags. Would it be possible to add version tags to the appropriate commits?

**Comment by adamrankin** [comment]
1.6 tagged, if you want previous versions tagged please list the version/commit pairs you would like

**Comment by Morwenn** [comment]
That was fast, thanks a lot! :)
