### ISSUE TITLE
How to  load a tool file and get tool's transform information ?

### ISSUE THREAD

**Issue by AustinYuAo** [PlusToolkit/ndicapi#27]
Hi, I'm using ndiBasicExample,  how can I load the tool file and get the tool transform information?

**Comment by adamrankin** [comment]
An example can be found here:
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx

In particular, look at:
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx#L297
https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/NDICAPITracking/vtkPlusNDITracker.cxx#L610

**Comment by aubest** [comment]
Thanks very much for your reply. After reading this example, I have written a test program. However, when I placed tool in a fixed position,I found a problem. The quaternion value of tool obtained by the test application was different from that obtained by the NDI official application.I took two photos, one is the result of NDI and the other is the result of test program. You can find that the quaternion values in the test program seem to be in a different order , comparing to the quaternion values in the official NDI application, and the x、y、z values are also exist differences
![test](https://user-images.githubusercontent.com/28101192/141108659-d0d61a3e-2ff3-49ce-aed8-a5091b78e8ba.jpg)
![NDI](https://user-images.githubusercontent.com/28101192/141108671-36feeb64-783f-4944-bc8c-6271d6dbdf2e.jpg)
.
