### ISSUE TITLE
ndicapi cannot open COM ports greater than COM10

### ISSUE THREAD

**Issue by UliBartels** [PlusToolkit/ndicapi#31]
This is an issue I ran into and got to the bottom today.
Microsoft only reserves the [COM1-COM9 file names](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file). When trying to open a COM port outside of this the name needs to be [prepended with "\\\\.\\"](https://support.microsoft.com/en-us/topic/howto-specify-serial-ports-larger-than-com9-db9078a5-b7b6-bf00-240f-f749ebfd913e) for the call to CreateFile to succeed.

ndicapi currently does not check for this, so on some machines the device will just refuse to connect.

**Comment by rajkundu** [comment]
Has this issue [been resolved](https://github.com/PlusToolkit/ndicapi/pull/32#issuecomment-1253071423)?

**Comment by adamrankin** [comment]
Yes, it was closed as already solved in #32

It is solved by 
https://github.com/PlusToolkit/ndicapi/blob/master/ndicapi.cxx#L619
