### ISSUE TITLE
Python API build failures

### ISSUE THREAD

**Issue by thompson318** [PlusToolkit/ndicapi#39]
Hello, I just tried rebuilding the python extensions after https://github.com/PlusToolkit/ndicapi/commit/60e1b39c7bd9b8f577d40173449b6edb22d7eb73. I get build failure on on all platforms, see https://github.com/SciKit-Surgery/ndicapi/actions/runs/6717927145. Example output from the Windows build, other platforms are similar:
> ndicapimodule.cxx(1788): error C2065: 'NDI_IRCHK_FAIL': undeclared identifier
ndicapimodule.cxx(1788): error C2660: 'PyDict_SetItemString': function does not take 2 arguments
C:\hostedtoolcache\windows\Python\3.7.9\x64\include\dictobject.h(162): note: see declaration of 'PyDict_SetItemString'
ndicapimodule.cxx(1788): note: while trying to match the argument list '(PyObject *, const char [15])'
ndicapimodule.cxx(1789): error C2065: 'NDI_FIRMWARE': undeclared identifier
ndicapimodule.cxx(1789): error C2660: 'PyDict_SetItemString': function does not take 2 arguments
C:\hostedtoolcache\windows\Python\3.7.9\x64\include\dictobject.h(162): note: see declaration of 'PyDict_SetItemString'
ndicapimodule.cxx(1789): note: while trying to match the argument list '(PyObject *, const char [13])'
ndicapimodule.cxx(1791): error C2065: 'NDI_IRINIT_FAIL': undeclared identifier
ndicapimodule.cxx(1791): error C2660: 'PyDict_SetItemString': function does not take 2 arguments
C:\hostedtoolcache\windows\Python\3.7.9\x64\include\dictobject.h(162): note: see declaration of 'PyDict_SetItemString'
ndicapimodule.cxx(1791): note: while trying to match the argument list '(PyObject *, const char [16])'
ndicapimodule.cxx(1793): error C2065: 'NDI_SROM_FAIL': undeclared identifier
ndicapimodule.cxx(1793): error C2660: 'PyDict_SetItemString': function does not take 2 arguments
C:\hostedtoolcache\windows\Python\3.7.9\x64\include\dictobject.h(162): note: see declaration of 'PyDict_SetItemString'
ndicapimodule.cxx(1793): note: while trying to match the argument list '(PyObject *, const char [14])'
ndicapimodule.cxx(1796): error C2065: 'NDI_SROM_SELECT': undeclared identifier
ndicapimodule.cxx(1796): error C2660: 'PyDict_SetItemString': function does not take 2 arguments
C:\hostedtoolcache\windows\Python\3.7.9\x64\include\dictobject.h(162): note: see declaration of 'PyDict_SetItemString'

Am I missing something here or is the Python module currently broken?

**Comment by adamrankin** [comment]
I am unfamiliar with the python module. Does it require manual changes after an update or is it autogenerated from code?

**Comment by adamrankin** [comment]
Ah, I see `https://github.com/PlusToolkit/ndicapi/blob/master/ndicapimodule.cxx`

Are you knowledgeable on how to fix it? There is no one on the team who currently supports the python extension

**Comment by thompson318** [comment]
I have a little knowledge. I'll try and take a deeper look. I'll have to fit it in around other stuff so may not be quick. From the error messages it looks like it could be quite easy to fix but we'll wait and see.

**Comment by adamrankin** [comment]
I'll take a look as well

**Comment by adamrankin** [comment]
I've updated the error codes in the module code

**Comment by adamrankin** [comment]
Could you try and a build and see if it's fixed in your environment?

**Comment by thompson318** [comment]
All the builds look good to me now, see https://github.com/SciKit-Surgery/ndicapi/actions/runs/6721816154 for more info. Thank you for the speedy fix. I haven't been able to test it on any NDI hardware yet though. Is it likely that any of the changes to support BX2 to will impact existing TX calls?

**Comment by adamrankin** [comment]
No, the way I coded it should have no impact on any other calls, including BX/TX/GX

**Comment by thompson318** [comment]
All looks good, thank you.
