### ISSUE TITLE
what is the rms for ndi dataframe?

### ISSUE THREAD

**Issue by busyyang** [PlusToolkit/ndicapi#45]
I'm very sorry to bother you. I would like to ask what the RMS in the NDI data frame means and how is it calculated, which is the last element of `double transform[8]` in `ndiGetTXTransform`.
~~~cpp
ndicapiExport int ndiGetTXTransform(ndicapi* pol, int portHandle, double transform[8])
~~~

 I know this is not information about NDI devices, but I don't know where to get this information. Maybe you will know.

**Comment by adamrankin** [comment]
You would have to reach out to NDI technical support to get a breakdown of their values. We just request them from the device.

https://support.ndigital.com/s/contactsupport
